#name: Release Terraform Provider Binaries
#on:
#  push:
#    tags:
#      - "v*.*.*"
#
#jobs:
#  release-matrix:
#    name: Release
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        go-version: [1.17.x ]
#        goos: [linux]
#        goarch: [amd64]
#
#    steps:
#      - name: Set env
#        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
#
#      - uses: actions/setup-go@v2
#        with:
#          go-version: ${{ matrix.go-version }} # The Go version to download (if necessary) and use.
#      - run: go version
#
#      - uses: actions/checkout@v2
#        with:
#          ref: ${{ env.RELEASE_VERSION }}
#
#
#      - name: Build binaries
#        run: |
#          ./build-release.sh ${{ env.RELEASE_VERSION }}
#          ls -la
#
#      # Publish to GitHub Commander Binary project
#      - name: Release Binaries
#        uses: svenstaro/upload-release-action@v2
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: terraform-provider-keeper_*
#          tag: ${{ env.RELEASE_VERSION }}
#          overwrite: true
#          file_glob: true
#          body: "Keeper Secrets Manager Terraform provider release ${{ env.RELEASE_VERSION }}"
