name: "Terraform Provider SBOM Publisher"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  sbom:
    name: "Generate SBOM for Terraform Provider"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

#      - name: Cleanup unwanted files and directories for scanning
#        run: |
#          echo "Removing unwanted directories..."
#          # Adapt these to your needs - removing any test directories or unrelated content
#          rm -rf .git/
#          rm -rf .github/
#
#          echo "Removing unwanted files..."
#          rm -f go.sum
#
#          echo "Listing remaining directories for verification..."
#          ls -la

      # Disable all catalogers except Go
      - name: Generate SBOM
        env:
          SYFT_PACKAGE_SEARCH_UNINDEXED_ARCHIVES: "true"
          SYFT_PACKAGE_SEARCH_INDEXED_ARCHIVES: "true"
          SYFT_SCOPE: "all-layers"
          SYFT_PACKAGE_CATALOGER_ENABLED: "true"
          SYFT_PACKAGE_CATALOGER_RUBY_ENABLED: "false"
          SYFT_PACKAGE_CATALOGER_PYTHON_ENABLED: "false"
          SYFT_PACKAGE_CATALOGER_NODEJS_ENABLED: "false"
          SYFT_PACKAGE_CATALOGER_DARTLANG_ENABLED: "false"
          SYFT_PACKAGE_CATALOGER_DOTNET_ENABLED: "false"
          SYFT_PACKAGE_CATALOGER_JAVA_ENABLED: "false"
          SYFT_PACKAGE_CATALOGER_LINUX_ENABLED: "false"
          SYFT_PACKAGE_CATALOGER_PHP_ENABLED: "false"
          SYFT_PACKAGE_CATALOGER_RUST_ENABLED: "false"
        run: |
          # Install Syft (Current Manifest CLI v0.18.3 release Syft v1.18.1)
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v1.18.1          
          echo "Syft version: $(syft version)"
          
          # Install Manifest CLI
          curl -sSfL https://raw.githubusercontent.com/manifest-cyber/cli/main/install.sh | sh -s -- -b /usr/local/bin v0.18.3          
          
          # Create Syft configuration focusing only on Go
          cat > syft-config.yaml << 'EOF'
          package:
            search:
              scope: all-layers
              exclude:
                - ".git/**"
                - ".github/**"
                - "**/testdata/**"
            cataloger:
              enabled: true
              ruby:
                enabled: false
              python:
                enabled: false
              nodejs:
                enabled: false
              dartlang:
                enabled: false
              dotnet:
                enabled: false
              java:
                enabled: false
              linux:
                enabled: false
              php:
                enabled: false
              rust:
                enabled: false
              golang:
                enabled: true
                search-unindexed-archives: true
                search-indexed-archives: true
          EOF
          
          # Get version from go.mod or use git tag
          VERSION=$(grep -oP "go [0-9]+\.[0-9]+(\.[0-9]+)?" go.mod | cut -d' ' -f2)
          if [ -z "$VERSION" ]; then
            VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
          fi
          
          # Debug: show what will be scanned
          echo "Files to be scanned:"
          find . -name "*.go" -o -name "go.mod" -o -name "go.sum"
          
          # Generate and publish SBOM using Manifest
          manifest sbom . \
            --generator=syft \
            --name=terraform-provider-secretsmanager \
            --version=${VERSION} \
            --output=spdx-json \
            --file=sbom.json \
            --api-key=${{ secrets.MANIFEST_TOKEN }} \
            --publish=true \
            --asset-label=terraform-provider,sbom-generated,golang \
            --generator-config=syft-config.yaml

      - name: Archive SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-terraform-provider
          path: |
            ./*.json
            ./*.xml
          retention-days: 10